### ISSUE TITLE
Printing the total of energy consumed and of CO2 generated  during the training phase of the algorithm. 

### ISSUE THREAD

**Issue by maxbaiw29** [fvaleye/tracarbon#204]
Dear Florian, 
Would it possible to add functions that print at the total of energy consumed and co2 generated from the entire training phase of the algorithm? Furthermore, can you also add one that print the carbon intensity derived from the CO2 signal API? 
Thank you, 
Best Regards, 
Max

**Comment by fvaleye** [comment]
Hello @maxbaiw29 👋,

Thank you for your message. 
After releasing the following PR #206, we can retrieve a report using `TracarbonReport`, which contains running statistics after stopping Tracarbon.

Here is an example of how to use it to measure energy consumption and carbon emission while running your algorithm:
```
from tracarbon import (
    CarbonEmissionGenerator,
    EnergyConsumptionGenerator,
    StdoutExporter,
    TracarbonBuilder,
    TracarbonConfiguration,
)

configuration = TracarbonConfiguration(co2signal_api_key="CO2SIGNAL_KEY")

metric_generators = [EnergyConsumptionGenerator(), CarbonEmissionGenerator()]
exporter = StdoutExporter(metric_generators=metric_generators)
tracarbon = TracarbonBuilder().with_exporter(exporter=exporter).build()
with tracarbon:
    # Your algorithm here

report = tracarbon.report # to get the report
```

If you would like more information, you could also use the DEBUG level using `TRACARBON_LOG_LEVEL=DEBUG` environment variable.
