### ISSUE TITLE
Add __main__.py for easier cli usage

### ISSUE THREAD

**Issue by corentinbettiol** [fvaleye/tracarbon#6]
# Description

Python modules are not necessarily in path, so we may want to use `python3 -m tracarbon run` instead of `tracarbon run`.

This led to an error.

The *actual* way of running tracarbon with Python where installed modules are not on path is `python3 -m tracarbon.cli.__init__`.

The *correct* way of running a Python package is `python3 -m [module_name]` (see [here](https://adamj.eu/tech/2020/02/25/use-python-m-pip-everywhere/) an example on "why it's better" with pip).

If we create a `__main__.py` file at the root of the package, then Python will call it by default using only the name of the package.

Here's a small example:
```python
$ mkdir a && nano a/__main__.py
$ cat a/__main__.py 
if __name__ == "__main__":
    print("Main!")
$ python3 a
Main!

```

**Comment by fvaleye** [comment]
Hello @corentinbettiol 👋,

Thank you for submitting this enhancement 👍 

I created a PR to improve the CLI usage based on your comment!

**Comment by corentinbettiol** [comment]
Thanks!
