### ISSUE TITLE
Missing `return` statements for linux & windows

### ISSUE THREAD

**Issue by corentinbettiol** [fvaleye/tracarbon#88]
# Environment

**Tracarbon version**: latest from pip

**Environment**:
- **OS**: kubuntu

***
# Bug

**What happened**:
```
File "/usr/local/lib/python3.10/dist-packages/tracarbon/hardwares/sensors.py", line 63, in from_platform
tracarbon.exceptions.TracarbonException: This platform Linux is not yet implemented.
```

**How to reproduce it**:

Launch tracarbon on linux (or windows).

**More details**:

The (simple) fix is to add a `return` [here](https://github.com/fvaleye/tracarbon/blob/main/tracarbon/hardwares/sensors.py#L61) and [here](https://github.com/fvaleye/tracarbon/blob/main/tracarbon/hardwares/sensors.py#L63) (`hardwares/sensors.py`, lines 61 & 63).

**Comment by fvaleye** [comment]
Hello @corentinbettiol 👋,

Thanks for reporting this issue! 

Do you want to create a Pull Request for this fix?

**Comment by corentinbettiol** [comment]
Hi, sorry I didn't have time for fixing this myself, thanks!
